#!/usr/bin/env node
/**
 * Generate THIRD-PARTY-NOTICES.txt for the chat-ui bundle.
 *
 * The chat-ui is distributed under the MIT License. Its dependencies are
 * permissive (MIT / ISC / BSD / Apache-2.0 / 0BSD), which permit that
 * redistribution ON CONDITION we preserve their copyright notices and license
 * text. This script walks node_modules, collects each package's license
 * declaration + bundled LICENSE file, and emits a single attribution file that
 * must ship alongside every build.
 *
 * Zero dependencies on purpose — it must run in any checkout without an extra
 * install. Run via `npm run notices` (wired into `npm run build`).
 */
import { readdirSync, readFileSync, existsSync, writeFileSync, statSync } from "node:fs";
import { join, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const NODE_MODULES = join(ROOT, "node_modules");
// Emit next to the source and into the built bundle dir so the artifact Drupal
// serves carries its attributions too.
const OUT_TARGETS = [join(ROOT, "THIRD-PARTY-NOTICES.txt"), join(ROOT, "..", "js", "dist", "THIRD-PARTY-NOTICES.txt")];

const LICENSE_FILE_RE = /^(LICENSE|LICENCE|COPYING)(\..*)?$/i;
const COPYLEFT_RE = /GPL|MPL|EPL|CDDL|SSPL|OSL|CPAL|-SA\b/i;

if (!existsSync(NODE_MODULES)) {
  console.error("[gen-notices] node_modules not found — run `npm install` first.");
  process.exit(1);
}

/** Enumerate every package dir, including scoped (@scope/name). */
function packageDirs() {
  const out = [];
  for (const name of readdirSync(NODE_MODULES)) {
    if (name === ".bin" || name === ".cache") continue;
    const p = join(NODE_MODULES, name);
    if (!statSync(p).isDirectory()) continue;
    if (name.startsWith("@")) {
      for (const scoped of readdirSync(p)) out.push(join(p, scoped));
    } else {
      out.push(p);
    }
  }
  return out;
}

function readLicenseText(dir) {
  for (const f of readdirSync(dir)) {
    if (LICENSE_FILE_RE.test(f)) {
      try { return readFileSync(join(dir, f), "utf8").trim(); } catch { /* ignore */ }
    }
  }
  return null;
}

const seen = new Map(); // name -> record
const copyleft = [];

for (const dir of packageDirs()) {
  const pkgJson = join(dir, "package.json");
  if (!existsSync(pkgJson)) continue;
  let pkg;
  try { pkg = JSON.parse(readFileSync(pkgJson, "utf8")); } catch { continue; }
  if (!pkg.name || !pkg.version) continue;
  const license = typeof pkg.license === "string"
    ? pkg.license
    : (pkg.license?.type || (Array.isArray(pkg.licenses) ? pkg.licenses.map((l) => l.type).join(" OR ") : "UNKNOWN"));
  if (COPYLEFT_RE.test(license)) copyleft.push(`${pkg.name}@${pkg.version} (${license})`);
  const key = `${pkg.name}@${pkg.version}`;
  if (seen.has(key)) continue;
  seen.set(key, { name: pkg.name, version: pkg.version, license, text: readLicenseText(dir) });
}

if (copyleft.length) {
  console.error("[gen-notices] COPYLEFT dependency detected — bundling it would relicense the MIT distributable:");
  for (const c of copyleft) console.error("  - " + c);
  process.exit(2);
}

const records = [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
const header = [
  "THIRD-PARTY SOFTWARE NOTICES",
  "",
  "The AIncient chat-ui console is licensed under the MIT License. It bundles the",
  "third-party packages listed below, each under its own permissive license,",
  "reproduced here as those licenses require.",
  "",
  `Generated by scripts/gen-notices.mjs — ${records.length} packages.`,
  "",
  "=".repeat(78),
  "",
].join("\n");

const body = records.map((r) => {
  const lines = [`${r.name}@${r.version}  —  ${r.license}`];
  if (r.text) lines.push("", r.text);
  lines.push("", "-".repeat(78), "");
  return lines.join("\n");
}).join("\n");

const content = header + body;
for (const target of OUT_TARGETS) {
  try {
    writeFileSync(target, content);
    console.log(`[gen-notices] wrote ${records.length} notices → ${target}`);
  } catch (e) {
    // dist may not exist during a source-only run; that's fine.
    console.warn(`[gen-notices] skipped ${target}: ${e.message}`);
  }
}
