<?php

namespace Drupal\aincient_deny\Routing;

use Drupal\Core\Routing\RouteSubscriberBase;
use Drupal\Core\Routing\RoutingEvents;
use Symfony\Component\Routing\RouteCollection;
use Drupal\Core\Access\AccessResult;
/**
 * Listens to the dynamic route events and alters the Block Layout access.
 */
class RouteSubscriber extends RouteSubscriberBase {

  /**
   * Paths the backend keeps reachable even when they sit under a denied prefix
   * (e.g. the metering settings form lives under the blanket-denied
   * '/admin/config'). A whitelist entry always beats the deny list — matched
   * exact OR as a prefix. Every path MUST start with '/'.
   */
  public const ALLOWED_PATHS = [
    '/admin/config/ai/ai-metering/settings',
  ];

  /**
   * Route paths the backend hides — matched exact OR as a prefix. Every path
   * MUST start with '/' (route paths always do; an entry without it never
   * matches anything).
   */
  public const DISALLOWED_PATHS = [
    '/node/add',
    '/admin/content',
    '/admin/content/media',
    '/admin/people/roles',
    '/admin/people/role-settings',
    '/admin/config',
    '/admin/reports/metatag-plugins',
    '/admin/reports/fields',
    '/admin/reports/updates',
    '/admin/reports/status',
    '/admin/reports/ai-metering/by-role',
    '/admin/people/permissions',
    '/admin/modules',
    '/admin/structure',
    '/admin/appearance',
    '/admin/content/files',
    '/admin/content/media-grid',
    '/admin/flowdrop',
    '/admin/reports/views-plugins',
  ];

  /**
   * {@inheritdoc}
   */
  public static function getSubscribedEvents(): array {
    // Run LAST (lower priority = later). View-backed admin routes such as
    // system.admin_content (/admin/content) and entity.media.collection
    // (/admin/content/media) are regenerated by Views' RouteSubscriber at
    // priority -175, which would otherwise wipe our access override and
    // restore the original _permission. Sit below that so our restriction
    // is the final word.
    $events[RoutingEvents::ALTER][] = ['onAlterRoutes', -300];
    return $events;
  }

  /**
   * Whether a route path is explicitly whitelisted (exact or prefix match).
   * A whitelist entry beats the deny list, so a reachable room can live under
   * an otherwise-denied prefix.
   */
  public static function isAllowedPath(string $path): bool {
    foreach (self::ALLOWED_PATHS as $path_prefix) {
      if ($path === $path_prefix || str_starts_with($path, $path_prefix)) {
        return TRUE;
      }
    }
    return FALSE;
  }

  /**
   * Whether a route path is on the deny list (exact or prefix match). An
   * explicit ALLOWED_PATHS entry always wins.
   */
  public static function isDeniedPath(string $path): bool {
    if (self::isAllowedPath($path)) {
      return FALSE;
    }
    foreach (self::DISALLOWED_PATHS as $path_prefix) {
      if ($path === $path_prefix || str_starts_with($path, $path_prefix)) {
        return TRUE;
      }
    }
    return FALSE;
  }

  /**
   * {@inheritdoc}
   */
  protected function alterRoutes(RouteCollection $collection) {
    foreach ($collection->all() as $route) {
      if (self::isDeniedPath($route->getPath())) {
        $this->restrictAccess($route);
      }
    }
  }

  protected function restrictAccess($route) {
    $requirements = $route->getRequirements();
    unset($requirements['_permission'], $requirements['_entity_access']);
    $route->setRequirements($requirements);
    $route->setRequirement('_custom_access', '\Drupal\aincient_deny\Routing\RouteSubscriber::accessCheck');
  }

  /**
   * Evaluates who can view the Block Layout screen.
   */
  public static function accessCheck() {
    // Returning 'forbidden' explicitly overrides Drupal's User 1 bypass rule.
    // The cache is invalidated per user context to ensure reliable state checks.
    return AccessResult::forbidden()->mergeCacheMaxAge(0);
  }

}
