<?php

/**
 * @file
 * Vendors AIncient's OWN fixed brand fonts as self-hosted woff2 + @font-face.
 *
 * Schibsted Grotesk (body/UI) and Fraunces (Atelier display serif) are part of
 * AIncient's product brand (docs/brand.md §2.4), loaded on the OPERATOR surfaces:
 * the chat console, the Studio Backend admin chrome, and the FlowDrop editor. Hot-linking
 * them from Google Fonts leaks the *operator's* IP on every backend page load —
 * exactly the privacy problem the self-hosted emoji font already avoids
 * (DECISIONS 0058). So we vendor them from our own origin too.
 *
 * Pulls Google's already-optimised, unicode-range-SUBSET woff2 chunks and
 * rewrites the CSS to local relative URLs, preserving font-style / font-weight /
 * unicode-range per @font-face block. Writes:
 *   - aincient_core/fonts/  → Schibsted only  (admin + FlowDrop chrome)
 *   - aincient_chat/fonts/  → Schibsted + Fraunces  (the console)
 * Each module ships the exports it serves (brand.md §2 "Masters vs. exports");
 * the small Schibsted duplication keeps the modules independently installable.
 *
 * Re-run to refresh the fonts; commit the regenerated fonts/. After re-running,
 * rebuild the console bundle (chat-ui: `npm run build`) — the console's
 * @font-face is served as a separate Drupal CSS, but styles.css must stay free
 * of the old Google @import.
 *
 * Pure CLI PHP (shells out to curl) — no Drupal bootstrap, no composer deps.
 */

declare(strict_types=1);

$coreModule = dirname(__DIR__);
$customDir = dirname($coreModule);
$coreFonts = $coreModule . '/fonts';
$chatFonts = $customDir . '/aincient_chat/fonts';
$pagesFonts = $customDir . '/aincient_pages/fonts';

foreach ([$coreFonts, $chatFonts, $pagesFonts] as $dir) {
  if (!is_dir($dir) && !mkdir($dir, 0755, TRUE) && !is_dir($dir)) {
    fwrite(STDERR, "Cannot create $dir\n");
    exit(1);
  }
}

// A real desktop UA so css2 serves woff2 subsets (not the legacy TTF fallback).
$ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  . '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';

$fetch = static function (string $url, ?string $out = NULL) use ($ua): string|bool {
  $cmd = 'curl -fsSL -A ' . escapeshellarg($ua)
    . ($out !== NULL ? ' -o ' . escapeshellarg($out) : '')
    . ' ' . escapeshellarg($url);
  $body = shell_exec($cmd);
  return $out !== NULL ? is_file($out) : (string) $body;
};

/**
 * Vendor one family: download its woff2 chunks into $dir and return the
 * generated @font-face CSS (with local relative URLs). Chunk files are named
 * "<slug>.<i>.woff2"; the local CSS uses the same family name as Google so the
 * existing font-family stacks resolve unchanged.
 */
$vendor = static function (string $cssUrl, string $family, string $slug, string $dir) use ($fetch): string {
  $css = (string) $fetch($cssUrl);
  if ($css === '') {
    fwrite(STDERR, "Failed to fetch $cssUrl\n");
    exit(1);
  }
  preg_match_all('/@font-face\s*\{([^}]*)\}/s', $css, $blocks);
  $out = '';
  $count = 0;
  foreach ($blocks[1] as $block) {
    if (!preg_match('/url\(([^)]+)\)/', $block, $u)) {
      continue;
    }
    $remoteUrl = trim($u[1], "'\" ");
    $file = "$slug.$count.woff2";
    if (!$fetch($remoteUrl, "$dir/$file")) {
      fwrite(STDERR, "Failed to download $remoteUrl\n");
      exit(1);
    }
    $style = preg_match('/font-style:\s*([^;]+);/', $block, $s) ? trim($s[1]) : 'normal';
    $weight = preg_match('/font-weight:\s*([^;]+);/', $block, $w) ? trim($w[1]) : '400';
    $range = preg_match('/unicode-range:\s*([^;]+);/', $block, $r) ? trim($r[1]) : '';
    $out .= "@font-face {\n"
      . "  font-family: '$family';\n"
      . "  font-style: $style;\n"
      . "  font-weight: $weight;\n"
      . "  font-display: swap;\n"
      . "  src: url($file) format('woff2');\n"
      . ($range !== '' ? "  unicode-range: $range;\n" : '')
      . "}\n";
    $count++;
  }
  if ($count === 0) {
    fwrite(STDERR, "No @font-face blocks parsed for $family — Google CSS format may have changed.\n");
    exit(1);
  }
  fwrite(STDERR, "  $family → $count chunk(s) in $dir\n");
  return $out;
};

$header = static fn(string $extra): string => "/* GENERATED by aincient_core/scripts/fetch-brand-fonts.php — DO NOT EDIT.\n"
  . "   Self-hosted AIncient brand fonts (served from our origin, not Google, so\n"
  . "   operator surfaces leak no IP — DECISIONS 0058 posture). $extra\n"
  . "   Re-run the script to refresh; commit the regenerated fonts/. */\n\n";

$schibstedUrl = 'https://fonts.googleapis.com/css2?family=Schibsted+Grotesk:ital,wght@0,400..700;1,400..700&display=swap';
$frauncesUrl = 'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400..600&display=swap';

// aincient_core: Schibsted only (admin chrome + FlowDrop editor brand layers).
fwrite(STDERR, "aincient_core/fonts:\n");
$coreCss = $header('Schibsted Grotesk for the admin + FlowDrop editor chrome.')
  . $vendor($schibstedUrl, 'Schibsted Grotesk', 'schibsted-grotesk', $coreFonts);
file_put_contents("$coreFonts/brand-fonts.css", $coreCss);

// aincient_chat: Schibsted (UI) + Fraunces (display serif) for the console.
fwrite(STDERR, "aincient_chat/fonts:\n");
$chatCss = $header('Schibsted Grotesk (UI) + Fraunces (display serif) for the Atelier console.')
  . $vendor($schibstedUrl, 'Schibsted Grotesk', 'schibsted-grotesk', $chatFonts)
  . $vendor($frauncesUrl, 'Fraunces', 'fraunces', $chatFonts);
file_put_contents("$chatFonts/console-fonts.css", $chatCss);

// aincient_pages: Schibsted (body) + Fraunces (display serif) — the out-of-box
// DEFAULT fonts for the PUBLIC site, always self-hosted (offline-first, no
// consent gate). Attached like the emoji font; operators may still swap via the
// brand studio (dynamic loader). Same families as the console, so the bridge
// from website → console keeps one typographic voice.
fwrite(STDERR, "aincient_pages/fonts:\n");
$pagesCss = $header('Schibsted Grotesk (body) + Fraunces (display serif) — the public site default fonts.')
  . $vendor($schibstedUrl, 'Schibsted Grotesk', 'schibsted-grotesk', $pagesFonts)
  . $vendor($frauncesUrl, 'Fraunces', 'fraunces', $pagesFonts);
file_put_contents("$pagesFonts/brand-fonts.css", $pagesCss);

fwrite(STDERR, "Done. Rebuild the console bundle (chat-ui: npm run build) after removing the Google @import.\n");
