import { ensureStudio } from "./flow";
import { DocLoadError } from "./page-state";
import { clearDocEnd } from "./doc-end-state";
import { MEDIA_STUDIO } from "./rooms-core";
import { apiUrl } from "./console-config";

/**
 * The Media studio store — the loaded image-media item being edited, and the two
 * non-AI writes over it (rename/alt, replace file).
 *
 * The media parallel of page-state's page/block draft, but far simpler: a media
 * item has no page schema, no live preview iframe, and no editor lock (it's not a
 * composed document — just an asset with metadata). One item is "open" at a time;
 * {@link loadMediaIntoStudio} is the single "edit this media item" entry point
 * (the Library card's Edit action + a `/atelier/media/<id>` deep link both reach
 * it through the console machine's doc-load path). Backed by the endpoints on
 * {@see \Drupal\aincient_pages\Controller\MediaController}.
 */

/** The editable detail of one image-media item (mirrors MediaRepository::detail). */
export type MediaDetail = {
  id: string;
  token: string;
  name: string;
  alt: string;
  thumb: string;
  /** Display-sized source URL — the studio renders the image at real size. */
  preview: string;
  mime: string;
  width: number;
  height: number;
  status: "published" | "unpublished";
};

let current: MediaDetail | null = null;
const subscribers = new Set<() => void>();
let version = 0;

/**
 * A suggested alt text the AI wrote for an item, waiting to be dropped into that
 * item's editor field. The vision tool NEVER saves (DECISIONS: "AI proposes, you
 * approve"); it stages the suggestion here, {@link MediaStudio} applies it to the
 * open item's alt field (dirty, unsaved), and the human reviews + Saves. Scoped by
 * `id` so a suggestion only lands on the item it was written for.
 */
let pendingAlt: { id: string; alt: string } | null = null;

/**
 * A suggested NAME the AI wrote for an item, waiting to be dropped into that item's
 * editor Name field — the naming twin of {@link pendingAlt}. The propose-name tool
 * NEVER saves (Law 11 + "AI proposes, you approve"); it stages the suggestion here,
 * {@link MediaStudio} applies it to the open item's Name field (dirty, unsaved), and
 * the human reviews + Saves. Scoped by `id` so it only lands on the item it names.
 */
let pendingName: { id: string; name: string } | null = null;

/**
 * When a generated EDIT result is open, the token of the image it was edited FROM.
 * Drives the editor rail's "Replace original" action (repoint the source's file at
 * the new bytes). Null for a from-scratch generation or a plain uploaded item.
 */
let editSource: { id: string; sourceToken: string } | null = null;

function emit(): void {
  version += 1;
  for (const cb of subscribers) cb();
}

/** The open media item, or null (nothing loaded / it was closed). */
export function getMediaDetail(): MediaDetail | null {
  return current;
}

/** A pending AI alt-text suggestion for the open item, or null. */
export function getPendingAlt(): { id: string; alt: string } | null {
  return pendingAlt;
}

/** Stage an AI alt-text suggestion for `id`; {@link MediaStudio} applies it. */
export function stageAltProposal(id: string, alt: string): void {
  pendingAlt = { id, alt };
  emit();
}

/** Drop a consumed / stale alt suggestion. */
export function clearPendingAlt(): void {
  if (pendingAlt === null) return;
  pendingAlt = null;
  emit();
}

/** A pending AI name suggestion for the open item, or null. */
export function getPendingName(): { id: string; name: string } | null {
  return pendingName;
}

/** Stage an AI name suggestion for `id`; {@link MediaStudio} applies it. */
export function stageNameProposal(id: string, name: string): void {
  pendingName = { id, name };
  emit();
}

/** Drop a consumed / stale name suggestion. */
export function clearPendingName(): void {
  if (pendingName === null) return;
  pendingName = null;
  emit();
}

/** The "edited from" source for the open item, when it's a generated edit result. */
export function getEditSource(): { id: string; sourceToken: string } | null {
  return editSource;
}

/** Record that the open item `id` was generated by editing `sourceToken`. */
export function setEditSource(id: string, sourceToken: string): void {
  editSource = { id, sourceToken };
  emit();
}

/** The open media item's id, or null. Read by console-nav's boot-room derivation. */
export function getMediaId(): string | null {
  return current?.id ?? null;
}

/** A monotonic version for useSyncExternalStore snapshots. */
export function mediaVersion(): number {
  return version;
}

/** Subscribe to media-store changes (load / save / replace / close). */
export function subscribeMedia(cb: () => void): () => void {
  subscribers.add(cb);
  return () => {
    subscribers.delete(cb);
  };
}

/**
 * Open an image-media item in the Media studio: fetch its editable detail, seed
 * it as the open item, and switch to the `media` studio. Throws {@link DocLoadError}
 * on a failed load (403 denied / 404 gone) so the console machine can land in its
 * dead-end pane — the same contract as loadPageIntoStudio / loadBlockIntoStudio.
 */
export async function loadMediaIntoStudio(id: string | number): Promise<void> {
  const res = await fetch(apiUrl(`/media/${encodeURIComponent(String(id))}/schema`), {
    credentials: "same-origin",
  });
  const data = await res.json().catch(() => null);
  if (!res.ok || !data?.id) {
    throw new DocLoadError(res.status, data?.error ?? `Couldn’t load media ${id} (HTTP ${res.status}).`);
  }
  clearDocEnd();
  // A fresh load abandons any suggestion/edit-source staged for a prior item — they
  // are scoped to one open item and must not leak across a navigation.
  if (pendingAlt && pendingAlt.id !== String(data.id)) pendingAlt = null;
  if (pendingName && pendingName.id !== String(data.id)) pendingName = null;
  if (editSource && editSource.id !== String(data.id)) editSource = null;
  current = data as MediaDetail;
  emit();
  ensureStudio(MEDIA_STUDIO);
}

/** Clear the open media item (close-on-leave). */
export function closeMedia(): void {
  if (current === null && pendingAlt === null && pendingName === null && editSource === null) return;
  current = null;
  pendingAlt = null;
  pendingName = null;
  editSource = null;
  emit();
}

/**
 * Save the open item's name and/or alt text. Only the passed keys are written
 * (the two controls save independently). Returns the fresh detail; throws with a
 * readable message on failure (the studio surfaces it).
 */
export async function saveMediaMetadata(fields: { name?: string; alt?: string }): Promise<MediaDetail> {
  if (!current) throw new Error("No media item is open.");
  const res = await fetch(apiUrl(`/media/${encodeURIComponent(current.id)}`), {
    method: "POST",
    credentials: "same-origin",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(fields),
  });
  const data = await res.json().catch(() => null);
  if (!res.ok || !data?.item) {
    throw new Error(data?.error ?? `Save failed (HTTP ${res.status}).`);
  }
  current = data.item as MediaDetail;
  emit();
  return current;
}

/**
 * Replace the open item's underlying file — same media id + `media:<id>` token,
 * so every page/block/chrome that embeds it now serves the new bytes. Alt text is
 * preserved server-side. Returns the fresh detail.
 */
export async function replaceMediaFile(file: File): Promise<MediaDetail> {
  if (!current) throw new Error("No media item is open.");
  const body = new FormData();
  body.append("file", file);
  const res = await fetch(apiUrl(`/media/${encodeURIComponent(current.id)}/file`), {
    method: "POST",
    credentials: "same-origin",
    body,
  });
  const data = await res.json().catch(() => null);
  if (!res.ok || !data?.item) {
    throw new Error(data?.error ?? `Replace failed (HTTP ${res.status}).`);
  }
  current = data.item as MediaDetail;
  emit();
  return current;
}

/**
 * Delete the open media item — the human's "discard" for a generated image they
 * don't want (the AI never discards its own expensive output; the human decides).
 * Clears the store on success so the studio empties; the caller navigates away
 * (e.g. back to the Library). A referenced token resolves to nothing after this
 * (embeds degrade gracefully); usage-safety is a deferred enhancement.
 */
export async function deleteMedia(): Promise<void> {
  if (!current) throw new Error("No media item is open.");
  const res = await fetch(apiUrl(`/media/${encodeURIComponent(current.id)}/delete`), {
    method: "POST",
    credentials: "same-origin",
  });
  if (!res.ok) {
    const data = await res.json().catch(() => null);
    throw new Error(data?.error ?? `Delete failed (HTTP ${res.status}).`);
  }
  closeMedia();
}

/**
 * Replace the ORIGINAL (the image the open item was edited from) with the open
 * item's bytes — the "commit this edit onto the original" action. The original
 * keeps its `media:<id>` token, so every page/block/chrome embedding it now serves
 * the edited bytes. Returns the fresh original detail; the caller decides whether
 * to open it or delete the now-redundant generated item.
 */
export async function replaceOriginalWithCurrent(): Promise<MediaDetail> {
  if (!current) throw new Error("No media item is open.");
  if (!editSource || editSource.id !== current.id) {
    throw new Error("This image wasn’t edited from another, so there’s no original to replace.");
  }
  const originalId = editSource.sourceToken.split(":").pop() ?? "";
  const res = await fetch(apiUrl(`/media/${encodeURIComponent(originalId)}/replace-from`), {
    method: "POST",
    credentials: "same-origin",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ from: current.token }),
  });
  const data = await res.json().catch(() => null);
  if (!res.ok || !data?.item) {
    throw new Error(data?.error ?? `Replace failed (HTTP ${res.status}).`);
  }
  return data.item as MediaDetail;
}
