// GENERATED by scripts/gen-tokens.mjs from aincient_core/tokens/*.json — DO NOT EDIT.
// The console's design-token names, by tier (docs/console-tokens.md, DECISIONS 0438).

/** Reference tier — what a colour IS. Only the system tier may reference these. */
export const REF_TOKENS = [
  "--ain-ref-color-amber-78",
  "--ain-ref-color-bistre-24",
  "--ain-ref-color-brick-52",
  "--ain-ref-color-brick-62",
  "--ain-ref-color-chalk-97",
  "--ain-ref-color-charcoal-20",
  "--ain-ref-color-charcoal-25",
  "--ain-ref-color-charcoal-28",
  "--ain-ref-color-charcoal-34",
  "--ain-ref-color-charcoal-46",
  "--ain-ref-color-cinnabar-49",
  "--ain-ref-color-cinnabar-55",
  "--ain-ref-color-cinnabar-66",
  "--ain-ref-color-cinnabar-72",
  "--ain-ref-color-coral-66",
  "--ain-ref-color-gesso-86",
  "--ain-ref-color-gesso-92",
  "--ain-ref-color-gesso-93",
  "--ain-ref-color-gesso-95",
  "--ain-ref-color-gesso-99",
  "--ain-ref-color-mint-74",
  "--ain-ref-color-ochre-60",
  "--ain-ref-color-ochre-72",
  "--ain-ref-color-stone-47",
  "--ain-ref-color-stone-55",
  "--ain-ref-color-stone-58",
  "--ain-ref-color-stone-62",
  "--ain-ref-color-stone-70",
  "--ain-ref-color-umber-12",
  "--ain-ref-color-umber-30",
  "--ain-ref-color-verdigris-52",
  "--ain-ref-color-verdigris-72",
  "--ain-ref-color-violet-58",
] as const;

/** System tier — what a value is FOR. Light/dark is a mode: same name, two values. */
export const SYSTEM_TOKENS = [
  "--ain-color-accent",
  "--ain-color-accent-hover",
  "--ain-color-accent-tint",
  "--ain-color-bg",
  "--ain-color-border",
  "--ain-color-border-strong",
  "--ain-color-danger",
  "--ain-color-focus-ring",
  "--ain-color-on-accent",
  "--ain-color-shadow",
  "--ain-color-success",
  "--ain-color-surface",
  "--ain-color-surface-raised",
  "--ain-color-text",
  "--ain-color-text-faint",
  "--ain-color-text-muted",
  "--ain-color-warning",
  "--ain-font-body",
  "--ain-font-display",
  "--ain-font-mono",
  "--ain-radius-lg",
  "--ain-radius-md",
  "--ain-radius-sm",
  "--ain-radius-xl",
  "--ain-size-column-max",
] as const;

/** Component tier — the named exceptions. */
export const COMPONENT_TOKENS = [
  "--ain-mark-band-1",
  "--ain-mark-band-2",
  "--ain-mark-band-3",
  "--ain-mark-band-4",
  "--ain-mark-ring",
  "--ain-panel-bar-height",
  "--ain-sidebar-width",
  "--ain-topbar-height",
] as const;

export type RefToken = (typeof REF_TOKENS)[number];
export type SystemToken = (typeof SYSTEM_TOKENS)[number];
export type ComponentToken = (typeof COMPONENT_TOKENS)[number];
/** Every token a stylesheet outside the system tier may use. */
export type ConsoleToken = SystemToken | ComponentToken;

/** Pre-0438 names, retired in 0.17.0 (no stylesheet defines them) — refused by the studio CSS rule, which names the replacement. */
export const RETIRED_TOKENS: Readonly<Record<string, ConsoleToken>> = {
  "--ain-bg": "--ain-color-bg",
  "--ain-surface": "--ain-color-surface",
  "--ain-surface-2": "--ain-color-surface-raised",
  "--ain-border": "--ain-color-border",
  "--ain-border-strong": "--ain-color-border-strong",
  "--ain-text": "--ain-color-text",
  "--ain-text-dim": "--ain-color-text-muted",
  "--ain-text-faint": "--ain-color-text-faint",
  "--ain-accent": "--ain-color-accent",
  "--ain-accent-2": "--ain-color-warning",
  "--ain-accent-hover": "--ain-color-accent-hover",
  "--ain-accent-muted": "--ain-color-accent-tint",
  "--ain-on-accent": "--ain-color-on-accent",
  "--ain-jade": "--ain-color-success",
  "--ain-danger": "--ain-color-danger",
  "--ain-shadow": "--ain-color-shadow",
  "--ain-band-1": "--ain-mark-band-1",
  "--ain-band-2": "--ain-mark-band-2",
  "--ain-band-3": "--ain-mark-band-3",
  "--ain-band-4": "--ain-mark-band-4",
  "--ain-radius": "--ain-radius-md",
  "--ain-max": "--ain-size-column-max",
  "--ain-sidebar-w": "--ain-sidebar-width",
  "--ain-topbar-h": "--ain-topbar-height",
  "--ain-bar-h": "--ain-panel-bar-height",
  "--ain-font": "--ain-font-body",
  "--ain-mono": "--ain-font-mono",
};
