<?php

/**
 * @file
 * Generates build/tokens.generated.css from design-tokens.yml.
 *
 * Pure PHP (Symfony Yaml from the project vendor/), NO Drupal bootstrap — so it
 * runs as a step in the asset build (`npm run build`) without a live site.
 *
 * Emits, from the single token registry:
 *   1. `@theme inline { … }` — the var→utility maps Tailwind v4 needs at build
 *      time (semantic colours → --color-*, font families → --font-*).
 *   2. `:root { … }` — base defaults for EVERY token (primitive literals,
 *      semantic/component as var() references), ordered primitive→semantic→
 *      component, so unbranded pages render and var() chains resolve.
 *
 * Both build/input.css files (module + theme) @import the result, so the token
 * surface stays identical across the module and the front-end theme.
 */

declare(strict_types=1);

use Symfony\Component\Yaml\Yaml;

require __DIR__ . '/../../../../../vendor/autoload.php';

$moduleDir = dirname(__DIR__);
$tokens = Yaml::parseFile($moduleDir . '/design-tokens.yml')['tokens'] ?? [];

$cssVar = static fn(string $name, array $def): string => $def['css_var'] ?? str_replace('_', '-', $name);

// ── Tier 0: the immutable Tailwind base palette ───────────────────────────
// Tailwind v4 ships its full default colour palette as --color-{hue}-{step}
// vars, but only emits the ones actually USED (tree-shaking), so the brand
// studio's swatch picker can't rely on the compiled output. Parse the source
// (node_modules/tailwindcss/theme.css) and re-emit the WHOLE palette to a
// dedicated :root file (always present, defeats tree-shaking) plus a JSON the
// studio renders swatches from. This is Tier 0: never edited, only referenced
// by Tier 1 palette tokens via var(--color-…).
[$paletteCss, $paletteJson] = build_palette($moduleDir . '/node_modules/tailwindcss/theme.css');
file_put_contents($moduleDir . '/build/tw-palette.generated.css', $paletteCss);
file_put_contents($moduleDir . '/build/tw-palette.json', $paletteJson);

// 1. @theme inline — the var→utility maps Tailwind needs to emit utilities:
//    semantic colours (--color-*), font families (--font-*), and any token with
//    an explicit `theme_key` (e.g. the font-size scale → --text-*, keeping its
//    paired default line-height so existing text-* utilities stay token-driven).
$theme = [];
foreach ($tokens as $name => $def) {
  $var = $cssVar($name, $def);
  if (!empty($def['theme_key'])) {
    $theme[] = "  --{$def['theme_key']}: var(--$var);";
    if (!empty($def['line_height'])) {
      $theme[] = "  --{$def['theme_key']}--line-height: {$def['line_height']};";
    }
    continue;
  }
  if (($def['tier'] ?? '') !== 'semantic') {
    continue;
  }
  // Some semantic colours are not surface utilities (e.g. the shadow tint) — they
  // opt out of the var→utility map so no stray `*-shadow-color` class is emitted.
  if (!empty($def['theme_skip'])) {
    continue;
  }
  if (($def['category'] ?? '') === 'color') {
    $theme[] = "  --color-$var: var(--$var);";
  }
  elseif (($def['type'] ?? '') === 'font-family') {
    $theme[] = "  --$var: var(--$var);";
  }
}

// 2. :root base defaults — every token, in tier order (Tier 0 lives in the
//    separate tw-palette file; the registry starts at Tier 1 = palette).
$order = ['palette' => [], 'semantic' => [], 'component' => []];
foreach ($tokens as $name => $def) {
  $tier = $def['tier'] ?? 'semantic';
  $order[$tier][] = "  --{$cssVar($name, $def)}: {$def['default']};";
}

$out = "/* GENERATED by scripts/build-tokens.php from design-tokens.yml — do not edit. */\n\n";
$out .= "@theme inline {\n" . implode("\n", $theme) . "\n}\n\n";
$out .= ":root {\n";
foreach (['palette', 'semantic', 'component'] as $tier) {
  $out .= "  /* $tier */\n" . implode("\n", $order[$tier]) . "\n";
}
$out .= "}\n";

$target = $moduleDir . '/build/tokens.generated.css';
file_put_contents($target, $out);
fwrite(STDERR, "Wrote $target (" . count($tokens) . " tokens)\n");

/**
 * Parse Tailwind's theme.css colour palette → [full :root CSS, swatch JSON].
 *
 * @return array{0: string, 1: string}
 */
function build_palette(string $themeCssPath): array {
  // Preferred display order: neutrals first, then the chromatic wheel. Any hue
  // present in theme.css but missing here is appended (so new Tailwind hues
  // still surface, just at the end).
  $hueOrder = [
    'slate', 'gray', 'zinc', 'neutral', 'stone', 'taupe', 'mauve', 'mist', 'olive',
    'red', 'orange', 'amber', 'yellow', 'lime', 'green', 'emerald', 'teal',
    'cyan', 'sky', 'blue', 'indigo', 'violet', 'purple', 'fuchsia', 'pink', 'rose',
  ];

  $css = is_file($themeCssPath) ? (string) file_get_contents($themeCssPath) : '';
  // --color-<hue>-<step>: <value>;  and the wordless --color-white/black.
  preg_match_all('/--color-([a-z]+)(?:-(\d+))?:\s*([^;]+);/i', $css, $m, PREG_SET_ORDER);

  $byHue = [];
  $base = [];
  foreach ($m as $row) {
    [$hue, $step, $value] = [$row[1], $row[2] ?? '', trim($row[3])];
    $cssName = $step === '' ? "color-$hue" : "color-$hue-$step";
    $swatch = ['step' => $step === '' ? $hue : $step, 'css_var' => $cssName, 'value' => $value];
    if ($step === '') {
      // white / black — single-tone anchors, grouped together.
      $base[] = $swatch;
    }
    else {
      $byHue[$hue][] = $swatch;
    }
  }

  // Emit the full palette to :root so every swatch resolves at runtime
  // regardless of which colours the Tailwind build happened to tree-shake.
  $decl = [];
  foreach ($base as $s) {
    $decl[] = "  --{$s['css_var']}: {$s['value']};";
  }
  foreach ($byHue as $swatches) {
    foreach ($swatches as $s) {
      $decl[] = "  --{$s['css_var']}: {$s['value']};";
    }
  }
  $cssOut = "/* GENERATED by scripts/build-tokens.php from tailwindcss/theme.css — do not edit. */\n"
    . "/* Tier 0: the immutable Tailwind base palette. Referenced by Tier 1 (palette) tokens; never edited directly. */\n\n"
    . ":root {\n" . implode("\n", $decl) . "\n}\n";

  // Order the groups for the picker; white/black ride along as a "base" group.
  $groups = [];
  if ($base) {
    $groups[] = ['hue' => 'base', 'label' => 'Base', 'swatches' => $base];
  }
  $ordered = array_keys($byHue);
  usort($ordered, static function (string $a, string $b) use ($hueOrder): int {
    $ia = array_search($a, $hueOrder, TRUE);
    $ib = array_search($b, $hueOrder, TRUE);
    $ia = $ia === FALSE ? PHP_INT_MAX : $ia;
    $ib = $ib === FALSE ? PHP_INT_MAX : $ib;
    return $ia <=> $ib ?: strcmp($a, $b);
  });
  foreach ($ordered as $hue) {
    $groups[] = ['hue' => $hue, 'label' => ucfirst($hue), 'swatches' => $byHue[$hue]];
  }

  $count = count($base) + array_sum(array_map('count', $byHue));
  fwrite(STDERR, "Parsed Tailwind palette ($count swatches, " . count($groups) . " groups)\n");

  return [$cssOut, json_encode(['groups' => $groups], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)];
}
