<?php

/**
 * @file
 * Vendors the self-hosted monochrome Noto Emoji web font under fonts/.
 *
 * The emoji font is ALWAYS loaded (agent content uses emoji and the user can't
 * opt out), so — unlike the brand fonts, which a user may point at a system
 * stack — it is the one web font that must not leak the visitor's IP to Google.
 * We therefore serve it from our OWN origin. This script pulls Google's already-
 * optimised, unicode-range-SUBSET woff2 chunks (the browser fetches only the
 * chunks whose emoji appear on a page) and rewrites the CSS to local relative
 * URLs. Re-run to refresh the font (commit the regenerated fonts/). See
 * decisions/DECISIONS.md 0058.
 *
 * Pure CLI PHP (shells out to curl) — no Drupal bootstrap, no composer deps.
 */

declare(strict_types=1);

$moduleDir = dirname(__DIR__);
$fontsDir = $moduleDir . '/fonts';
if (!is_dir($fontsDir) && !mkdir($fontsDir, 0755, TRUE) && !is_dir($fontsDir)) {
  fwrite(STDERR, "Cannot create $fontsDir\n");
  exit(1);
}

// A real desktop UA so css2 serves woff2 subsets (not the legacy TTF fallback).
$ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
  . '(KHTML, like Gecko) Chrome/120.0 Safari/537.36';
$cssUrl = 'https://fonts.googleapis.com/css2?family=Noto+Emoji';

$fetch = static function (string $url, ?string $out = NULL) use ($ua): string|bool {
  $cmd = 'curl -fsSL -A ' . escapeshellarg($ua)
    . ($out !== NULL ? ' -o ' . escapeshellarg($out) : '')
    . ' ' . escapeshellarg($url);
  $body = shell_exec($cmd);
  return $out !== NULL ? is_file($out) : (string) $body;
};

$css = (string) $fetch($cssUrl);
if ($css === '') {
  fwrite(STDERR, "Failed to fetch $cssUrl\n");
  exit(1);
}

// Each @font-face block carries one woff2 url + (usually) a unicode-range.
preg_match_all('/@font-face\s*\{([^}]*)\}/s', $css, $blocks);

$out = "/* GENERATED by scripts/fetch-emoji-font.php — DO NOT EDIT.\n"
  . "   Self-hosted monochrome Noto Emoji (served from our origin, not Google,\n"
  . "   so the always-on emoji font leaks no visitor IP — DECISIONS 0058).\n"
  . "   Re-run the script to refresh; commit the regenerated fonts/. */\n\n";

$count = 0;
foreach ($blocks[1] as $block) {
  if (!preg_match('/url\(([^)]+)\)/', $block, $u)) {
    continue;
  }
  $remoteUrl = trim($u[1], "'\" ");
  $file = "noto-emoji.$count.woff2";
  if (!$fetch($remoteUrl, "$fontsDir/$file")) {
    fwrite(STDERR, "Failed to download $remoteUrl\n");
    exit(1);
  }
  $range = preg_match('/unicode-range:\s*([^;]+);/', $block, $r) ? trim($r[1]) : '';
  $out .= "@font-face {\n"
    . "  font-family: 'Noto Emoji';\n"
    . "  font-style: normal;\n"
    . "  font-weight: 400;\n"
    . "  font-display: swap;\n"
    . "  src: url($file) format('woff2');\n"
    . ($range !== '' ? "  unicode-range: $range;\n" : '')
    . "}\n";
  $count++;
}

if ($count === 0) {
  fwrite(STDERR, "No @font-face blocks parsed — Google CSS format may have changed.\n");
  exit(1);
}

file_put_contents($fontsDir . '/noto-emoji.css', $out);
fwrite(STDERR, "Wrote $count subset chunks + noto-emoji.css to $fontsDir\n");
